== APPENDIX: Setting up my own machine for the lab
:experimental:

The labs were designed to run entirely on OpenShift, so you don't have to install anything in your desktop. 

The following instructions provide guidance for anyone who wants to run the code on their on environment. 

=== Java Development Kit

We need a JDK 11+ installed on our machine. The latest JDK can be downloaded from:

* http://openjdk.java.net/install/[OpenJDK]

You can use either Oracle JDK or OpenJDK.

=== Apache Maven

You need Apache Maven 3.5+. If you don't have it already:

* Download Apache Maven from https://maven.apache.org/download.cgi.
* Unzip to a directory of your choice and add it to the `PATH`.


=== IDE

We recommend you to use an IDE. You can use any Java IDE like Eclipse, IntelliJ or VS Code.
For a similar experience as in the workshop, use VS Code.

=== Getting the code

The code used in the lab can be found in the following Github repository:

[source]
----
git clone https://github.com/redhat-na-ssa/dg8-workshop-labs.git
----



