---
become_override: false
ocp_username: opentlc-mgr
silent: false
workshop_openshift_project_postfix: cache
workshop_openshift_project_postfix2: cache2
workshop_labs_file: "_dg8-workshop-guides.yml"
workshop_labs_url: "https://raw.githubusercontent.com/redhat-na-ssa/dg8-workshop/refs/heads/4.18/docs"
verify_tls: false
workshop_access_token: datagrid
